[package]
name = "fell"
version = "0.1.0"
edition = "2021"

[profile.dev.package."*"]
# Compile dependencies with optimizations on even in debug mode.
opt-level = 3

[profile.no-opt]
inherits = "dev"
opt-level = 0

[profile.release]
debug = 0
strip = "symbols"
lto = true
opt-level = 3
codegen-units = 1

[dependencies]
anyhow = "1.0.86"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
human_bytes = "0.4.3"
humantime = "2.1.0"
libc = "0.2.155"
procfs = "0.16.0"
ratatui = "0.28.0"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros", "sync"] }
