[package]
name = "fell"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
crossterm = { version = "0.28.1", features = ["event-stream"] }
futures = "0.3.30"
ratatui = "0.27.0"
sysinfo = "0.31.2"
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros", "sync"] }
